### ISSUE TITLE
Solc bug

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#217]
soljson-v0.6.6+commit.6c089d02.js:1 ../wasm/soljson-v0.6.6+commit.6c089d02.js ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at requireFromString (/home/app/node_modules/require-from-string/index.js:28:4)
    at IncomingMessage.<anonymous> (/home/app/node_modules/solc/wrapper.js:338:35)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by chriseth** [comment]
Sorry about that, it was an error in the binary repository - it should be fixed now.

**Comment by edisinovcic** [comment]
Ah ok, I thought that I created this somehow. Tnx!
