### ISSUE TITLE
Monitor errors cause crashes

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#428]
```
{"name":"Ethereum Testnet Görli","hostname":"b3167ddf18e3","pid":18,"level":50,"loc":"[PROCESS_BLOCK:FAILED]","blockNumber":3934338,"msg":"Invalid JSON RPC response: \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"","time":"2021-03-18T10:38:23.677Z","v":0}
{"name":"Matic Mainnet","hostname":"b3167ddf18e3","pid":18,"level":30,"loc":"[PROCESS_BLOCK]","blockNumber":12162735,"getBlockPause":922.9599817706417,"msg":"Waiting for new blocks","time":"2021-03-18T10:38:24.035Z","v":0}
{"name":"Ethereum Testnet Görli","hostname":"b3167ddf18e3","pid":18,"level":50,"loc":"[PROCESS_BLOCK:FAILED]","blockNumber":3934338,"msg":"Invalid JSON RPC response: \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"","time":"2021-03-18T10:38:24.205Z","v":0}
{"name":"xDAI Chain","hostname":"b3167ddf18e3","pid":18,"level":30,"loc":"[PROCESS_BLOCK]","blockNumber":15071831,"getBlockPause":2896.6437973668812,"msg":"Waiting for new blocks","time":"2021-03-18T10:38:24.339Z","v":0}
{"name":"Celo Mainnet","hostname":"b3167ddf18e3","pid":18,"level":30,"loc":"[PROCESS_BLOCK]","blockNumber":5697556,"getBlockPause":2633.312543060801,"msg":"Waiting for new blocks","time":"2021-03-18T10:38:25.304Z","v":0}
{"name":"Ethereum Testnet Görli","hostname":"b3167ddf18e3","pid":18,"level":50,"loc":"[PROCESS_BLOCK:FAILED]","blockNumber":3934340,"msg":"Invalid JSON RPC response: \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"","time":"2021-03-18T10:38:25.769Z","v":0}
{"name":"Matic Mainnet","hostname":"b3167ddf18e3","pid":18,"level":30,"loc":"[PROCESS_BLOCK]","blockNumber":12162736,"getBlockPause":922.9599817706417,"msg":"Waiting for new blocks","time":"2021-03-18T10:38:26.070Z","v":0}
{"name":"Celo Alfajores Testnet","hostname":"b3167ddf18e3","pid":18,"level":30,"loc":"[PROCESS_BLOCK]","blockNumber":4143768,"getBlockPause":3186.3081771035704,"msg":"Waiting for new blocks","time":"2021-03-18T10:38:26.091Z","v":0}
{"name":"Matic Testnet Mumbai","hostname":"b3167ddf18e3","pid":18,"level":30,"loc":"[PROCESS_BLOCK]","blockNumber":11701077,"getBlockPause":1898.7491679162063,"msg":"Waiting for new blocks","time":"2021-03-18T10:38:26.275Z","v":0}
{"name":"Ethereum Testnet Görli","hostname":"b3167ddf18e3","pid":18,"level":50,"loc":"[PROCESS_BLOCK:FAILED]","blockNumber":3934340,"msg":"Invalid JSON RPC response: \"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"","time":"2021-03-18T10:38:26.295Z","v":0}
{"name":"Celo Baklava Testnet","hostname":"b3167ddf18e3","pid":18,"level":30,"loc":"[PROCESS_BLOCK]","blockNumber":4548207,"getBlockPause":2393.920493691637,"msg":"Waiting for new blocks","time":"2021-03-18T10:38:27.303Z","v":0}
/home/app/node_modules/web3-core-helpers/lib/formatters.js:403
    throw new Error(`Provided address ${address} is invalid, the capitalization checksum test failed, or it's an indirect IBAN address which can't be converted.`);
    ^

Error: Provided address 2 is invalid, the capitalization checksum test failed, or it's an indirect IBAN address which can't be converted.
    at Method.inputAddressFormatter (/home/app/node_modules/web3-core-helpers/lib/formatters.js:403:11)
    at /home/app/node_modules/web3-core-method/lib/index.js:129:38
    at Array.map (<anonymous>)
    at Method.formatInput (/home/app/node_modules/web3-core-method/lib/index.js:127:32)
    at Method.toPayload (/home/app/node_modules/web3-core-method/lib/index.js:160:23)
    at Eth.send [as getCode] (/home/app/node_modules/web3-core-method/lib/index.js:498:61)
    at Timeout.ChainMonitor.processBytecode [as _onTimeout] (/home/app/dist/monitor/monitor.js:80:35)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ethereum-sourcify@1.0.0 monitor:start: `node ./dist/monitor/monitor.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ethereum-sourcify@1.0.0 monitor:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-18T10_38_27_981Z-debug.log

> ethereum-sourcify@1.0.0 monitor:start /home/app
> node ./dist/monitor/monitor.js

web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
Error: Invalid JSON RPC response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
Error: Invalid JSON RPC response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
/home/app/services/verification/node_modules/solc/soljson.js:1
null;var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var nodeFS;var nodePath;if(ENVIRONMENT_IS_NODE){if(ENVIRONM

RuntimeError: abort(Error: Invalid JSON RPC response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/home/app/services/verification/node_modules/solc/soljson.js:1:13939)
    at process.emit (events.js:198:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
    at process._tickCallback (internal/process/next_tick.js:69:34)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ethereum-sourcify@1.0.0 monitor:start: `node ./dist/monitor/monitor.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ethereum-sourcify@1.0.0 monitor:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-18T10_38_50_838Z-debug.log

> ethereum-sourcify@1.0.0 monitor:start /home/app
> node ./dist/monitor/monitor.js
```

**Comment by FabijanC** [comment]
closed via https://github.com/ethereum/sourcify/pull/429
