### ISSUE TITLE
Can't verify contract and got error message `Failed to fetch`

### ISSUE THREAD

**Issue by Boyuan-Chen** [ethereum/sourcify#711]
```
POST https://sourcify.dev/server 400 (Bad Request)
Access to fetch at 'https://sourcify.dev/server' from origin 'https://legacy.sourcify.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
POST https://sourcify.dev/server net::ERR_FAILED 413
TypeError: Failed to fetch
    at verifier.ts:43:32
    at Generator.next (<anonymous>)
    at main.c39a9ca283d4d843bedf.js:45:14335
    at new Promise (<anonymous>)
    at r (main.c39a9ca283d4d843bedf.js:45:14080)
    at Object.e.verify (verifier.ts:35:77)
    at Verifier.tsx:222:28
    at Generator.next (<anonymous>)
    at main.c39a9ca283d4d843bedf.js:37:9546
    at new Promise (<anonymous>)
```

**Comment by kuzdogan** [comment]
What were you doing when you got this? I thought it was a short server downtime but it seems a CORS issue. Curious what caused it

**Comment by Boyuan-Chen** [comment]
What I found is that the file size that I tried to upload is too large, so the server returned the error code. I didn't encounter this issue before the new UI is up, so my solution for this is to copy and paste the metadata from the debug file that is generated by the hardhat to a `.json` file and upload it.
