### ISSUE TITLE
playground.sourcify.dev breaks when selecting Arbitrum One network

### ISSUE THREAD

**Issue by samajammin** [ethereum/sourcify#726]
https://playground.sourcify.dev/

Screen goes blank after selecting Arbitrum One (chain ID 42161):

<img width="1000" alt="Screen Shot 2022-05-11 at 11 09 48 AM" src="https://user-images.githubusercontent.com/8097623/167813771-827b2712-175b-436e-b098-d481cd5a21ea.png">

Console error:
```
react-dom.production.min.js:216 Error: invalid network chainId (argument="network", value={}, code=INVALID_ARGUMENT, version=networks/5.5.0)
    at e.value (index.ts:225:28)
    at e.value (index.ts:237:20)
    at e.value (index.ts:241:21)
    at er (index.ts:229:20)
    at value (base-provider.ts:703:16)
    at new a (base-provider.ts:623:34)
    at a.<anonymous> (createSuper.js:12:24)
    at new a (json-rpc-provider.ts:346:9)
    at App.js:89:18
    at Id (react-dom.production.min.js:262:359)
```

**Comment by samajammin** [comment]
Ah, probably should have created this in https://github.com/sourcifyeth/metadata-playground

The GH link on https://playground.sourcify.dev/ brought me here 😄

**Comment by kuzdogan** [comment]
Both fixed with https://github.com/sourcifyeth/metadata-playground/commit/be8e9b46dc06ecb4c1ac8eab98b10be9e3a575b6 :) thanks
