### ISSUE TITLE
test/chains/deployContracts.js can not work any more

### ISSUE THREAD

**Issue by lolieatapple** [ethereum/sourcify#989]
```
$ node test/chains/deployContracts.js --chainId 999 --privateKey 0x0a50*******220
/workspaces/sourcify/dist/common/EventManager.js:16
        return this.listeners[event].map((listener) => listener(...args));
                                     ^

TypeError: Cannot read properties of undefined (reading 'map')
    at EventManager.trigger (/workspaces/sourcify/dist/common/EventManager.js:16:38)
    at setRepositoryPath (/workspaces/sourcify/dist/config.js:40:49)
    at Object.<anonymous> (/workspaces/sourcify/dist/config.js:55:15)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/workspaces/sourcify/test/helpers/helpers.js:1:27)

Node.js v19.8.1
```

**Comment by marcocastignoli** [comment]
Thanks for the report @lolieatapple, I fixed this with this comit: https://github.com/ethereum/sourcify/commit/b69c940224d87fa3f93f5d9b123ae42bf93ab861
